#!/usr/bin/env bash

set -euo pipefail

readonly MDBOOK_VERSION="0.5.2"
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
readonly APPENDIX_DIR="$REPO_ROOT/docs/book/src/appendix"

cd "$REPO_ROOT"

if ! command -v mdbook >/dev/null 2>&1; then
    echo "mdbook v${MDBOOK_VERSION} is required" >&2
    exit 1
fi

actual_version="$(mdbook --version)"
if [[ "$actual_version" != "mdbook v${MDBOOK_VERSION}" ]]; then
    echo "expected mdbook v${MDBOOK_VERSION}, found ${actual_version}" >&2
    exit 1
fi

mkdir -p "$APPENDIX_DIR"

copy_with_header() {
    local source="$1"
    local destination="$2"
    local temporary="${destination}.tmp"

    if [[ ! -f "$source" ]]; then
        echo "missing documentation source: $source" >&2
        exit 1
    fi

    awk -v source="$source" \
        'BEGIN { print "<!-- Generated by scripts/build-book.sh from " source ". Do not edit this copy. -->"; print "" } { print }' \
        "$source" >"$temporary"
    mv "$temporary" "$destination"
}

copy_with_header "docs/contracts.md" "$APPENDIX_DIR/contracts.md"
copy_with_header "docs/porting-guide.md" "$APPENDIX_DIR/porting-guide.md"
copy_with_header "docs/roadmap.md" "$APPENDIX_DIR/roadmap.md"

if [[ -f "conformance/.artifacts/report.md" ]]; then
    copy_with_header \
        "conformance/.artifacts/report.md" \
        "$APPENDIX_DIR/conformance-report.md"
else
    printf '%s\n' \
        '<!-- Generated by scripts/build-book.sh because conformance/.artifacts/report.md was absent. Do not edit this copy. -->' \
        '' \
        '# Differential conformance report' \
        '' \
        'No conformance artifact was present for this local book build.' \
        '' \
        'The GitHub Pages workflow builds the Zig conformance runner, runs the' \
        'pinned TypeScript/Zig differential suite, and copies its per-surface' \
        'report here before mdBook runs. To populate the page locally, run:' \
        '' \
        '```sh' \
        'npm ci --prefix conformance' \
        'zig build conformance-runner' \
        'npm run --prefix conformance conformance' \
        'bash scripts/build-book.sh' \
        '```' \
        >"$APPENDIX_DIR/conformance-report.md"
fi

mdbook build docs/book

if command -v node >/dev/null 2>&1; then
    node scripts/check-book-highlight.mjs
else
    echo "warning: node not found; skipping book syntax-highlighting check" >&2
fi
